# Generated by Django 4.1.7 on 2023-03-06 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comment", "0003_alter_comment_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="target",
            field=models.CharField(max_length=100, verbose_name="评论目标"),
        ),
    ]
