# Generated by Django 4.1.7 on 2023-03-10 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comment", "0004_alter_comment_target"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={
                "ordering": ["-create_time"],
                "verbose_name": "评论",
                "verbose_name_plural": "评论",
            },
        ),
    ]
