# Generated by Django 4.1.7 on 2023-03-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_category_options_alter_post_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="tag",
            field=models.ManyToManyField(to="blog.tag", verbose_name="新标签"),
        ),
    ]
