# Generated by Django 4.1.7 on 2023-03-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_post_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="content_html",
            field=models.TextField(blank=True, editable=False, verbose_name="正文html代码"),
        ),
    ]
